config/routes.rb
TrelloTrack::Application.routes.draw do

  resources :projects, :only => [:index, :edit, :update, :destroy]
  resources :users, :only => [:index, :edit, :update, :destroy]

  root 'reporting#daily'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/reporting' => 'reporting#daily'
  get '/reporting/daily(/:year/:month/:day)' => 'reporting#daily', as: :daily
  get '/reporting/weekly(/:year/:week)' => 'reporting#weekly', as: :weekly
  get '/reporting/monthly(/:year/:month)' => 'reporting#monthly', as: :monthly
  get '/reporting/custom/from(/:year_from/:month_from/:day_from)/to(/:year_to/:month_to/:day_to)' => 'reporting#custom', as: :custom

  get '/settings' => 'settings#index', as: :settings

  get '/extensions' => 'tasks#extensions', as: :extensions
  get '/account' => 'users#account', as: :account

  resources :tasks, :except => [:index, :show] do
    member do
      post 'stop'
      post 'continue'
    end
  end

  namespace :api, defaults: {format: 'json'} do
    get '/timer' => 'timer#in_progress'
    get '/timer/last' => 'timer#last_task'
    post '/timer/create' => 'timer#create'
    post '/timer/stop' => 'timer#stop'
    post '/timer/continue' => 'timer#continue'
  end


end

app/views/partials/_filters.html.erb
<% if @user.admin? %>
  <div class="row filters hidden-print">
    <form id="filter">
        <%= select_tag "users", options_from_collection_for_select(@users, "id", "name", params[:users]),
                                :multiple => true, :id => "users_select",
                                :data => {:placeholder => "Filter by users"},
                                :class => "span5 pull-right"
                                %>

        <%= select_tag "projects", options_from_collection_for_select(@projects, "id", "name", params[:projects]),
                                :multiple => true, :id => "projects_select",
                                :data => {:placeholder => "Filter by projects"},
                                :class => "span5 pull-right"
                                %>
    </form>
  </div>
<% end %>

app/views/partials/_tasks_table.html.erb
<% if @tasks.empty? %>
  <h4 style="text-align: center">There are no tasks between<br>
    <%= @start_time.strftime('%d.%m.%Y, %H:%M') %><br>
    and<br>
    <%= @human_end_time.strftime('%d.%m.%Y, %H:%M') %>
  </h4>
<% else %>
  <table class="table table-striped table-list table-report">

    <thead>
      <tr>
        <%= '<th>User</th>'.html_safe if @filtering_users_len %>
        <%= '<th>Project</th>'.html_safe if @filtering_projects_len %>
        <th>Activity</th>
        <%= '<th>Date</th>'.html_safe unless controller.action_name == 'daily' %>
        <th>Duration</th>
        <th class="hidden-print">Actions</th>
      </tr>
    </thead>

    <tbody>

      <% @tasks.each do |task| %>
        <%
          start_time = task.start_time_capped_by(@start_time)
          end_time = task.end_time_capped_by(@end_time)
          space_for_activity = 7
        -%>
        <tr>
          <% if @filtering_users_len %>
            <% space_for_activity -= 2 %>
            <td class="span2">
              <span class="user">
                <%= task.user.name %>
              </span>
            </td>
          <% end %>
          <% if @filtering_projects_len %>
            <% space_for_activity -= 2 %>
            <td class="span2">
              <span class="project">
                <%= task.project.name %>
              </span>
            </td>
          <% end %>
          <td class="span<%= space_for_activity %>">
            <span class="activity">
              <%= task.name %>
            </span>
          </td>
          <% unless controller.action_name == 'daily' %>
            <td class="span2">
              <h5 class="started_at">
                <%= smart_date(start_time, @start_time, @end_time) %>
              </h5>
              <% unless end_time.nil? %>
                <% if start_time.day != (end_time -1.seconds).day %>
                  <h5 class="ended_at">
                    <%= smart_date(end_time, @start_time, @end_time) %>
                  </h5>
                <% end %>
              <% end %>
            </td>
          <% end %>
          <% if false %>
          <td class="span1">
            <h5 class="started_at">
              <%= '<span class="icon-arrow-left" title="Activity start time is outside of this time frame."></span>'.html_safe if task.over(@start_time) %>
              <%= task.start_time_capped_by(@start_time).strftime("%H:%M") %>
              <%= '<span class="icon-arrow-right" title="Activity end time is outside of this time frame."></span>'.html_safe if task.over(@end_time) %>
            </h5>
          </td>
          <% end %>
          <td class="span2">
            <h5 class="time-spent" >
              <% unless task.end_time.nil? %>
                <%= seconds_to_human_time(task.total_time_capped_by(@start_time, @end_time)) %>
                <% '<span title="In this time frame.">*</span>'.html_safe if task.over(@end_time) or task.over(@start_time) %>
              <% else %>
                In progress
              <% end %>
            </h5>
          </td>

          <td class="span1 hidden-print">
            <div class="btn-group">
              <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-edit icon-white"></i>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <% if task.not_finished.nil? %>
                  <li>
                    <%= link_to '<i class="icon-edit"></i> Details & Edit'.html_safe, edit_task_path(task.id) %>
                  </li>
                  <li>
                    <%= link_to '<i class="icon-play"></i> Continue'.html_safe, continue_task_path(task.id), method: :post, data: { confirm: 'Continue selected task?' }  %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to '<i class="icon-stop"></i> Stop timer'.html_safe, stop_task_path(task.id), method: :post, data: { confirm: 'Stop timer?' } %>
                  </li>
                <% end %>
                <li>
                  <%= link_to '<i class="icon-trash"></i> Destroy'.html_safe, task, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              </ul>
            </div>
          </td>

        </tr>

      <% end %>

    </tbody>

  </table>
<hr>
<div class="row total">
  <div class="span2 pull-right">
    <h4 id="total_time"><%= seconds_to_human_time(@total_seconds) %></h4>
  </div>
  <div class="span1 pull-right">
    <h4>Total: </h4>
  </div>
</div>
<% end %>

app/views/partials/_time_record_table.html.erb
<% if @records.empty? %>
  <h4 style="text-align: center">There are no records between<br>
    <%= @start_time.strftime('%d.%m.%Y, %H:%M') %><br>
    and<br>
    <%= @human_end_time.strftime('%d.%m.%Y, %H:%M') %>
  </h4>
<% else %>
  <table class="table table-striped table-list">

    <thead>
      <tr>
        <th>Activity</th>
        <th>Time</th>
        <th>Duration</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>

      <% @records.each do |record| %>
        <tr>

          <td class="row-fluid span6">
            <ul class="breadcrumb row-fluid span10">
              <li>
                <blockquote class="pull-left">
                  <p class="pull-left">
                    <%= record.name %>
                  </p>
                </blockquote>
              </li>
            </ul>
          </td>

          <td class="row-fluid span2">
            <div class="row-fluid span12">
              <blockquote>
                <h5 class="started_at">
                  <%= '<span class="icon-arrow-left" title="Activity continues..."></span>'.html_safe if record.over(@start_time) %>
                  <%= format_with_day(record.start_time_capped_by(@start_time), record.start_time_capped_by(@start_time), record.end_time_capped_by(@end_time)) %>
                </h5>
              </blockquote>
              <blockquote>
                <h5 class="ended_at">
                  <%= (format_with_day(record.end_time_capped_by(@end_time), record.start_time_capped_by(@start_time), record.end_time_capped_by(@end_time))) unless record.end_time.nil? %>
                  <%= '<span class="icon-arrow-right" title="Activity continues..."></span>'.html_safe if record.over(@end_time) %>
                </h5>
              </blockquote>
            </div>
          </td>

          <td class="row-fluid span3">
            <h5 class="time-spent" >
              <%= record.human_total_time_capped_by(@start_time, @end_time)[:diff] unless record.end_time.nil? %>
              <%= '<span title="Activity continues...">*</span>'.html_safe if record.over(@end_time) or record.over(@start_time) %>
            </h5>
          </td>

          <td class="row-fluid span1">
            <div class="btn-group">
              <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-edit icon-white"></i>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to '<i class="icon-edit"></i> Details & Edit'.html_safe, edit_time_record_path(record.id) %>
                </li>
                <li>
                  <%= link_to '<i class="icon-trash"></i> Destroy'.html_safe, record, method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
              </ul>
            </div>
          </td>

        </tr>

      <% end %>

    </tbody>

  </table>
<hr>
<div class="container row">
  <div class="span3 pull-right">
    <h4 id="total_time"><%= "%02d:%02d:%02d" % [(@total_seconds / 3600).to_i, ((@total_seconds % 3600) / 60).to_i, (@total_seconds % 60).to_i] %></h4>
  </div>
  <div class="span1 pull-right">
    <h4>Total:</h4>
  </div>
</div>
<% end %>