config/routes.rb
TrelloTrack::Application.routes.draw do

  resources :projects, :only => [:index, :edit, :update, :destroy]
  resources :users, :only => [:index, :edit, :update, :destroy]

  root 'reporting#daily'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/reporting' => 'reporting#daily'
  get '/reporting/daily(/:year/:month/:day)' => 'reporting#daily', as: :daily
  get '/reporting/weekly(/:year/:week)' => 'reporting#weekly', as: :weekly
  get '/reporting/monthly(/:year/:month)' => 'reporting#monthly', as: :monthly
  get '/reporting/custom/from(/:year_from/:month_from/:day_from)/to(/:year_to/:month_to/:day_to)' => 'reporting#custom', as: :custom

  get '/settings' => 'settings#index', as: :settings

  get '/extensions' => 'tasks#extensions', as: :extensions
  get '/account' => 'users#account', as: :account

  resources :tasks, :except => [:index, :show] do
    member do
      post 'stop'
      post 'continue'
    end
  end

  namespace :api, defaults: {format: 'json'} do
    get '/timer' => 'timer#in_progress'
    get '/timer/last' => 'timer#last_task'
    post '/timer/create' => 'timer#create'
    post '/timer/stop' => 'timer#stop'
    post '/timer/continue' => 'timer#continue'
  end


end

app/models/project.rb
class Project < ActiveRecord::Base

  def name
    read_attribute(:name) || board_id
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_filter :require_admin

  def index
    @projects = Project.all
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_url, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :board_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :board_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Board</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.board_id %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>