config/routes.rb
TrelloTrack::Application.routes.draw do

  resources :projects, :only => [:index, :edit, :update, :destroy]
  resources :users, :only => [:index, :edit, :update, :destroy]

  root 'reporting#daily'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy', as: :logout

  get '/reporting' => 'reporting#daily'
  get '/reporting/daily(/:year/:month/:day)' => 'reporting#daily', as: :daily
  get '/reporting/weekly(/:year/:week)' => 'reporting#weekly', as: :weekly
  get '/reporting/monthly(/:year/:month)' => 'reporting#monthly', as: :monthly
  get '/reporting/custom/from(/:year_from/:month_from/:day_from)/to(/:year_to/:month_to/:day_to)' => 'reporting#custom', as: :custom

  get '/settings' => 'settings#index', as: :settings

  get '/extensions' => 'tasks#extensions', as: :extensions
  get '/account' => 'users#account', as: :account

  resources :tasks, :except => [:index, :show] do
    member do
      post 'stop'
      post 'continue'
    end
  end

  namespace :api, defaults: {format: 'json'} do
    get '/timer' => 'timer#in_progress'
    get '/timer/last' => 'timer#last_task'
    post '/timer/create' => 'timer#create'
    post '/timer/stop' => 'timer#stop'
    post '/timer/continue' => 'timer#continue'
  end


end

app/views/layouts/_footer.html.erb
<footer>

  <div class="container">
    <p class="muted credits">
      <%= link_to 'Trello Track', 'https://github.com/majjacz/trello_track' %> by <%= link_to 'Majjacz', 'mailto:majjacz@gmail.com' %> &copy; <%= Date.today.year %>
    </p>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header>


  <!-- Navbar -->
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to 'Trello Track'.html_safe, '/', class: 'brand' %>
        <ul class="nav">
          <li <%='class="active"'.html_safe if controller_name == 'tasks' and (controller.action_name == 'new' or controller.action_name == 'extensions') %>><%= link_to 'Tracking', new_task_path %></li>
          <li <%='class="active"'.html_safe if controller_name == 'reporting' %>><%= link_to 'Reporting', daily_path %></li>
          <% if current_user.admin? %>
            <li <%='class="active"'.html_safe if controller_name == 'settings' or controller_name == 'users' %>><%= link_to 'Settings', settings_path %></li>
          <% end %>
        </ul>
        <ul class="nav pull-right">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= image_tag(avatar_url(current_user.avatar_hash),:alt => current_user.name, :width => 35, :height => 35, class: 'gravatar') %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="nav-header"><%= current_user.name %></li>
              <li class="divider"></li>
              <li><%= link_to 'My Account', account_path %></li>
              <li><%= link_to 'Sign Out', logout_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>


  <!-- Subnav -->
  <div class="subnav subnav-fixed">
    <ul class="nav nav-pills">
        <% if controller_name == 'tasks' %>
          <li <%='class="active"'.html_safe if controller.action_name == 'new' %>><%= link_to 'Add Manually', new_task_path %></li>
          <li <%='class="active"'.html_safe if controller.action_name == 'extensions' %>><%= link_to 'Chrome extension', extensions_path %></li>
        <% end %>
        <% if controller_name == 'reporting' %>
          <li <%='class="active"'.html_safe if controller.action_name == 'daily' %>><%= link_to 'Daily', daily_path %></li>
          <li <%='class="active"'.html_safe if controller.action_name == 'weekly' %>><%= link_to 'Weekly', weekly_path %></li>
          <li <%='class="active"'.html_safe if controller.action_name == 'monthly' %>><%= link_to 'Monthly', monthly_path %></li>
          <li <%='class="active"'.html_safe if controller.action_name == 'custom' %>><%= link_to 'Custom', custom_path %></li>
        <% end %>
        <% if controller_name == 'settings' or controller_name == 'users' or controller_name == 'projects'%>
          <li <%='class="active"'.html_safe if controller.action_name == 'index' and controller_name == 'settings' %>><%= link_to 'Application', settings_path %></li>
          <li <%='class="active"'.html_safe if controller_name == 'users' %>><%= link_to 'Users', users_path %></li>
          <li <%='class="active"'.html_safe if controller_name == 'projects' %>><%= link_to 'Projects', projects_path %></li>
        <% end %>
    </ul>
  </div>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloTrack</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= controller_name %>">

    <div id="wrap">

      <%= render 'layouts/header' %>


      <div id="main">
        <div class="container">

          <% flash.each do |name, msg| %>
            <% if name == :notice || name == :error %>
              <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                <a class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
              </div>
            <% end %>
          <% end %>

          <%= yield %>

        </div>
      </div>

    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>